service: pokeapiproxy

provider:
  name: aws
  runtime: dotnet8
  region: us-east-1
  memorySize: 1024
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/PokemonsTable

package:
  artifact: bin/Release/net8.0/publish/pokeapiproxy.zip

functions:
  api:
    handler: PokeApiProxy
    events:
      - http:
          path: /{proxy+}
          method: any
          
resources:
  Resources:
    PokemonsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PokemonsTable
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: N
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
